### ISSUE TITLE
stop server error 

### ISSUE THREAD

**Issue by Colin6618** [rom1504/node-minecraft-wrap#1]
........Server Started !
...[11:42:07] [Server thread/INFO]: Stopping the server
.[11:42:07] [Server thread/INFO]: Stopping server
.[11:42:07] [Server thread/INFO]: Saving players
.[11:42:07] [Server thread/INFO]: Saving worlds
.[11:42:07] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
.[11:42:07] [Server thread/INFO]: Saving chunks for level 'world'/Nether
.[11:42:07] [Server thread/INFO]: Saving chunks for level 'world'/The End
.[11:42:07] [Server Shutdown Thread/INFO]: Stopping server
.[11:42:07] [Server Shutdown Thread/INFO]: Saving players
.2015-09-25 11:42:07,354 ERROR Attempted to append to non-started appender ServerGuiConsole
.Exception in thread "Server Shutdown Thread" org.apache.logging.log4j.core.appender.AppenderLoggingException: Attempted to append to non-started appender ServerGuiConsole
.	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
.	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:425)
.	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:406)
.	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:367)
.	at org.apache.logging.log4j.core.Logger.log(Logger.java:110)
.	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1011)
.	at net.minecraft.server.MinecraftServer.t(SourceFile:381)
.	at net.minecraft.server.MinecraftServer$2.run(SourceFile:715)
Server Stopped !
Server data deleted !

**Comment by rom1504** [comment]
That's a Minecraft bug (see https://bugs.mojang.com/plugins/servlet/mobile#issue/MC-38134 ) so we can't fix it.
But that's basically a warning and it doesn't cause any problems for us.

**Comment by Colin6618** [comment]
Thanks ~
