### ISSUE TITLE
Handle the vanilla client too

### ISSUE THREAD

**Issue by rom1504** [rom1504/node-minecraft-wrap#4]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/281

**Comment by rom1504** [comment]
see http://wiki.vg/Wrapper_List

**Comment by rom1504** [comment]
https://logs.rom1504.fr/parts/169.txt has some info, for example

https://s3.amazonaws.com/Minecraft.Download/versions/1.9-pre2/1.9-pre2.jar

Also think about downloading/parsing the version list from mojang api.

**Comment by rom1504** [comment]
http://wiki.vg/Game_Files

**Comment by rom1504** [comment]
see https://gist.github.com/Gjum/a0e17504bd791293e5ed50557a91a957

**Comment by rom1504** [comment]
also see https://github.com/PrismarineJS/minecraft-data/issues/185#issuecomment-311327951

**Comment by rom1504** [comment]
https://stackoverflow.com/a/15562373

**Comment by rom1504** [comment]
https://coding.net/u/ncbql/p/minecraft-launcher/git/blob/master/lib/launch.js

**Comment by plexigras** [comment]
https://gist.github.com/anonymous/6a8c3c111cbcc9a09f2dfaaa7ef1e167

**Comment by rom1504** [comment]
now done
